# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-23 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='CoursePageViews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamps', models.TextField()),
                ('reg_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Analysis.Analysis')),
            ],
        ),
        migrations.CreateModel(
            name='MainPageViews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamps', models.TextField()),
                ('reg_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Analysis.Analysis')),
            ],
        ),
        migrations.CreateModel(
            name='MarkPageViews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamps', models.TextField()),
                ('reg_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Analysis.Analysis')),
            ],
        ),
    ]
