# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-23 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursepageviews',
            name='reg_no',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='mainpageviews',
            name='reg_no',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='markpageviews',
            name='reg_no',
            field=models.CharField(max_length=9),
        ),
        migrations.DeleteModel(
            name='Analysis',
        ),
    ]
